[project]
authors = ["Jermiah Joseph <jermiahjoseph98@gmail.com>"]
channels = ["conda-forge", "bioconda"]
name = "snakemake-developer"
platforms = ["osx-arm64", "osx-64", "linux-64", "win-64"]
version = "0.1.0"

[tasks]
setup = "./scripts/setup.sh"
add-upstream = "./scripts/add-upstream.sh"

[dependencies]
